backend:
  name: git-gateway
display_url: http://www.hexagonbio.com
publish_mode: editorial_workflow
# media_folder: "site/static/img" # Folder where user uploaded files should go
media_library:
  name: uploadcare
  config:
    publicKey: 9e007d301f6ad1c6a146
    uploadcare_tabs: file url gdrive dropbox
#public_folder: "img"

collections: # A list of collections the CMS should be able to edit
  - name: "news" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "News" # Used in the UI, ie.: "New Post"
    folder: "site/content/news" # The path to the folder where the documents are stored
    preview: false
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Link", name: "link", widget: "string"}
      - {label: "Publication", name: "pub", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Intro", name: "description", widget: "text"}
      - {label: "Image", name: "image", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown", required: false}
  - name: "careers" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Careers" # Used in the UI, ie.: "New Post"
    folder: "site/content/careers" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Intro", name: "description", widget: "text"}
      - {label: "Image", name: "image", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "pages"
    label: "Pages"
    preview: false
    files:
      - file: "site/content/_index.md"
        label: "Home Page"
        name: "home"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: "Intro", name: intro, widget: object, fields: [
              {label: "Heading", name: "heading", widget: string},
              {label: "Text", name: "text", widget: "text"}]}
          - {label: "Icons", name: icons, widget: list, fields: [
              {label: "Image", name: "image", widget: "image"},
              {label: "Heading", name: "heading", widget: string},
              {label: "Text", name: "text", widget: "text"}]}
          - {label: "Careers", name: "careers", widget: "object", fields: [
              {label: "Image", name: "image", widget: "image"},
              {label: "Heading", name: "heading", widget: string},
              {label: "Text", name: "text", widget: "text"}]}
      - file: "site/content/team/_index.md"
        label: "Team Page"
        name: "team"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Subtitle, name: subtitle, widget: string}
          - label: Leadership
            name: leaders
            widget: object
            fields:
              - {label: Heading, name: heading, widget: string}
              - label: Bios
                name: bios
                widget: list
                fields:
                  - {label: Name, name: name, widget: string}
                  - {label: Title, name: title, widget: string}
                  - {label: Text, name: text, widget: text}
                  - {label: Image, name: image, widget: image}
                  - {label: Profile Link, name: link, widget: string, required: false}
          - label: Advisors
            name: advisors
            widget: object
            fields:
              - {label: Heading, name: heading, widget: string}
              - label: Bios
                name: items
                widget: list
                fields:
                  - {label: Name, name: name, widget: string}
                  - {label: Title, name: title, widget: string}
                  - {label: Profile Link, name: link, widget: string, required: false}
          - label: Investors
            name: investors
            widget: object
            fields:
              - {label: Heading, name: heading, widget: string}
              - label: Logos
                name: items
                widget: list
                fields:
                  - {label: Image, name: image, widget: image}
          # - {label: Pricing, name: pricing, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: string}, {label: Plans, name: plans, widget: list, fields: [{label: Plan, name: plan, widget: string}, {label: Price, name: price, widget: string}, {label: Description, name: description, widget: string}, {label: Items, name: items, widget: list}]}]}
      - file: "site/content/about/_index.md"
        label: "About Page"
        name: "about"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Subtitle, name: subtitle, widget: string}
          - {label: Intro, name: intro, widget: text}
          - label: Approach
            name: approach
            widget: object
            fields:
              - {label: Title, name: main, widget: string}
              - {label: Intro, name: intro, widget: text}
              - {label: Heading, name: heading, widget: string}
              - {label: Text, name: text, widget: text}
          - label: Icons
            name: icons
            widget: list
            fields:
              - {label: Heading, name: heading, widget: string}
              - {label: Text, name: text, widget: text}
              - {label: Image, name: image, widget: image}
          - label: Publications
            name: pubs
            widget: object
            fields:
              - {label: Heading, name: heading, widget: string}
              - label: Papers
                name: items
                widget: list
                fields:
                  - {label: "Title", name: "title", widget: "string"}
                  - {label: "Link", name: "link", widget: "string"}
                  - {label: "Journal", name: "pub", widget: "string"}
                  - {label: "Publish Date", name: "date", widget: "datetime"}
                  - {label: "Authors", name: "description", widget: "text"}
          - label: Partners
            name: partners
            widget: object
            fields:
              - {label: Heading, name: heading, widget: string}
              - {label: Text 1, name: text1, widget: text}
              - {label: Text 2, name: text2, widget: text, required: false}
      - file: "site/content/contact/_index.md"
        label: "Contact Page"
        name: "contact"
        fields:
          - {label: "Title", name: title, widget: string}
          - {label: "Intro", name: intro, widget: string}
          - {label: "Map", name: map, widget: image}
          - {label: "Map Link", name: link, widget: string}
          - {label: "Location", name: location, widget: text}
          - {label: "Inquiries", name: inquiries, widget: text}
